use_frameworks!

platform :ios, '8.0'

target 'ZTTextFieldLibrary_Example' do
  pod 'ZTTextFieldLibrary', :path => '../'

  target 'ZTTextFieldLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
